name: robprog
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - myst-parser
  - recommonmark
  - scipy
  - seaborn
  - pytest
  - flake8
  - ipython
  - pytest-cov


